Afrik/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include("index.urls", namespace='index')),
    path('admin/', admin.site.urls),
    path("__reload__/", include("django_browser_reload.urls")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

index/urls.py
from django.urls import path
from .import views

app_name = 'index'


urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('services/', views.services, name='services'),
    path('blog/', views.blog, name='blog'),
    path('contact/', views.contact, name='contact'),
    path('mannual/', views.mannual, name='mannual'),
]

index/models.py
from django.db import models

# Create your models here.

index/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.core.mail import send_mail, EmailMessage
from django.conf import settings
from django.contrib import messages 

# Create your views here.

def home(request):
    return render(request, "index.html")


def about(request):
    return render(request, "about.html")

def services(request):
    return render(request, "services.html")

def blog(request):
    return render(request, "blog.html")

def contact(request):
    
    if request.method == "POST":  
        fullname = request.POST.get('fullname')
        email = request.POST.get('email')
        subject = request.POST.get('subject')
        msg = request.POST.get('message')
   
        message = f"""
                <div style="display: flex; justify-content: start; align-items: center; padding: 8px;">
                    <div style="padding: 16px; width: fit-content;">
                        <div style="text-align: start;">
                            <p>{fullname}, {email}</p>
                            <p>{msg}</p>  
                        </div>
                        <div style="margin-top: 24px; text-align: start;">
                            <p>© 2023 Afrikbook™. All Rights Reserved.</p>
                            <p><a href="afrikbook.com" style="color: #007BFF;">Afrikbook.com</a></p>
                        </div>
                    </div>
                </div>
            """

        try:
            send = send_email(email, subject, message)
            
            messages.success(request, "Your message was sent, thank you!")
        except Exception as e:
            messages.success(request, e)
        
    # else:
    

    return render(request, "contact.html")

def mannual(reqest):
    return render(reqest, "mannual.html")






def send_email(email, title, message):
   
    email_to_send  = EmailMessage(
        subject=title, 
        body=message, 
        from_email=settings.EMAIL_HOST_USER, 
        to=[settings.EMAIL_HOST_USER], 
        reply_to=[email],
    )
    email_to_send.content_subtype = "html"
    result = email_to_send .send(fail_silently=False,)
    # if result == len(email):
    #     return True
    # else:
    #     return False

index/templates/about.html
{% extends 'base.html' %}

{% block content %}

<section class="flex justify-center hero-wrap hero-wrap-2 h-full  mb-6" style="background-image: url('/media/images/bg_22.png');" data-stellar-background-ratio="0.5">
    <div class="overlay"></div>
    
    <div class="container w-7/12">
      <div class="flex items-center no-gutters slider-text align-items-end">
        <div class="col-md-9 ftco-animate pb-5">
            <p class="breadcrumbs mb-2"><span class="mr-2"><a href="{% url 'index:home'%}">Home <i class="ion-ios-arrow-forward"></i></a></span> <span>About<i class="ion-ios-arrow-forward"></i></span></p>
          <h1 class="mb-0 bread">About</h1>
        </div>
      </div>
    </div>
</section>
<section class="flex justify-center  my-6 py-6">   
    <div class="w-10/12 md:w-7/12">
      <div class="flex items-center no-gutters slider-text align-items-end">
        <div class="col-md-9 ftco-animate pb-5">
          <h1 class="mb-0 text-lg">About</h1>
          <p class="text-md font-sans text-gray-600 leading-loose">
            Spacesoft Integral System Ltd. proudly introduces our advanced accounting software, a comprehensive and user-friendly solution designed to revolutionize financial management for businesses of all sizes. This cutting-edge tool combines ease of use with powerful features, making it an essential asset for managing your financial operations efficiently and effectively.
            Our software is built to handle the complexities of modern accounting with ease, offering automated solutions for bookkeeping, invoicing, expense tracking, payroll processing, and financial reporting. The intuitive interface ensures a seamless user experience, allowing business owners and accountants to focus more on growth and decision-making rather than being bogged down by manual financial tasks.
          </p>
          <p class="text-md font-sans text-gray-600 leading-loose">
            Spacesoft Integral System Ltd. is committed to innovation and excellence, and this software exemplifies our dedication to providing world-class solutions that empower businesses to succeed. Let us handle the numbers, so you can focus on achieving your goals.
          </p>
        </div>
      </div>
      <div class="flex items-center no-gutters slider-text align-items-end">
        <div class="col-md-9 ftco-animate pb-5">
          <h1 class="mb-0 text-lg">Who Can Benefit</h1>
          <p class="text-md font-sans text-gray-600 leading-loose">Our software is ideal for small business owners, accountants, freelancers, and growing enterprises seeking an efficient, all-in-one accounting solution. With minimal setup and a short learning curve, it is accessible to those without extensive financial expertise, making it the perfect tool for entrepreneurs looking to manage their own finances.</p>
          <p class="text-md font-sans text-gray-600 leading-loose">Our accounting software stands out for its ease of use, powerful features, and commitment to data security. Embrace the future of accounting and simplify your financial management today.</p>
        </div>
      </div>
    </div>
</section>

{% include 'components/first.html' %}

<!-- {% include 'components/acheivements.html' %} -->

{% include 'components/signup.html' %}

<!-- {% include 'components/testimonies.html' %} -->


{% endblock content %}

index/templates/blog.html
{% extends 'base.html' %}

{% block content %}

<section class="flex justify-center hero-wrap hero-wrap-2 h-full border mb-6" style="background-image: url('/media/images/bg_2.jpg');" data-stellar-background-ratio="0.5">
    <div class="overlay"></div>
    
    <div class="container w-7/12">
      <div class="flex items-center no-gutters slider-text align-items-end">
        <div class="col-md-9 ftco-animate pb-5">
            <p class="breadcrumbs mb-2"><span class="mr-2"><a href="index.html">Home <i class="ion-ios-arrow-forward"></i></a></span> <span>Blog <i class="ion-ios-arrow-forward"></i></span></p>
          <h1 class="mb-0 bread">Blog</h1>
        </div>
      </div>
    </div>
</section>


{% endblock content %}

index/templates/contact.html
{% extends 'base.html' %}

{% block content %}

<section class="flex justify-center hero-wrap hero-wrap-2 h-full "
    style="background-image: url('/media/images/bg_22.png');" data-stellar-background-ratio="0.5">
    <div class="overlay"></div>

    <div class="container w-7/12">
        <div class="flex items-center no-gutters slider-text align-items-end">
            <div class="col-md-9 ftco-animate pb-5">
                <p class="breadcrumbs mb-2"><span class="mr-2"><a href="{% url 'index:home'%}">Home <i
                                class="ion-ios-arrow-forward"></i></a></span> <span>Contact Us <i
                            class="ion-ios-arrow-forward"></i></span></p>
                <h1 class="mb-0 bread">Contact Us</h1>
            </div>
        </div>
    </div>
</section>
<style>
    
</style>

<section class="bg-gray-200 flex justify-center py-8">
    <div class="w-full">
        <div class="flex justify-center">
            <div class="w-10/12 md:w-8/12">
                <div class="wrapper font-sans">
                    <div class="flex flex-col md:flex-row border bg-white">
                        <div class="h-[600px] w-full lg:w-7/12">
                            <div class="contact-wrap w-100 p-md-5 p-4">
                                <h3 class="mb-4 font-semibold text-xl text-primary ftco-animate">Get in touch</h3>
                                <div id="form-message-warning" class="mb-4"></div>
                                {% for message in messages %}
                                    <div id="form-message-success" class="mb-4 {% if message.tags == 'success' %} text-green-600 {%else%} text-red-500 {% endif %}">
                                         {{message}}
                                    </div>
                                {% endfor %}
                                <form method="POST" action="#">
                                    {% csrf_token %}
                                    <div class="">
                                        <div class="mb-4">
                                            <div class="flex flex-col">
                                                <label class="label" for="name">Full Name</label>
                                                <input type="text" class="border-b border-gray-300 outline-none  focus:border-0 active:border-0 focus:outline-none" name="fullname" id="name"
                                                    placeholder="Name" required>
                                            </div>
                                        </div>
                                        <div class="mb-4">
                                            <div class="flex flex-col">
                                                <label class="label" for="email">Email Address</label>
                                                <input type="email" class="border-b border-gray-300 outline-none  focus:border-0 active:border-0 focus:outline-none" name="email" id="email"
                                                    placeholder="Email" required>
                                            </div>
                                        </div>
                                        <div class="mb-4">
                                            <div class="flex flex-col">
                                                <label class="label" for="subject">Subject</label>
                                                <input type="text" class="border-b border-gray-300 outline-none  focus:border-0 active:border-0 focus:outline-none" name="subject" id="subject"
                                                    placeholder="Subject" required>
                                            </div>
                                        </div>
                                        <div class="mb-4">
                                            <div class="flex flex-col">
                                                <label class="label" for="#">Message</label>
                                                <textarea name="message" class="border-b border-gray-300 outline-none  focus:border-0 active:border-0 focus:outline-none" id="message" cols="30"
                                                    rows="4" placeholder="Message" required></textarea>
                                            </div>
                                        </div>
                                        <div class="mt-6">
                                            <div class="form-group">
                                                <input type="submit" value="Send Message" class="bg-primary w-full py-2">
                                                <div class="submitting"></div>
                                            </div>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                        <div class="h-[600px] w-full lg:w-5/12  bg-primary">
                            <div class="info-wrap  w-full p-md-5 p-4">
                                <h3 class="mb-4 font-semibold text-xl">Let's get in touch</h3>
                                <p class="mb-9">We're open for any suggestion or just to have a chat</p>
                                <div class="flex items-center mb-6">
                                    <div class="flex justify-center border rounded-full  py-5 px-6">
                                        <span class="fa fa-map-marker w-3"></span>
                                    </div>
                                    <div class="text pl-3">
                                        <p><span>Address:</span> 14 Dennis Osadebe Way, Asaba, Delta State</p>
                                    </div>
                                </div>
                                <div class="flex items-center mb-6">
                                    <div class="flex justify-center border rounded-full  py-5 px-6">
                                        <span class="fa fa-phone w-3"></span>
                                    </div>
                                    <div class="text pl-3">
                                        <p><span>Phone:</span> <a href="tel://09068734840">+234 906873 4840</a></p>
                                    </div>
                                </div>
                                <div class="flex items-center mb-6">
                                    <div class="flex justify-center border rounded-full  py-5 px-6">
                                        <span class="fa fa-paper-plane w-3"></span>
                                    </div>
                                    <div class="text pl-3">
                                        <p><span>Email:</span> <a href="mailto:afrikbook@gmail.com">afrikbook@gmail.com</a>
                                        </p>
                                    </div>
                                </div>
                                <div class="flex items-center mb-6">
                                    <div class="flex justify-center border rounded-full  py-5 px-6">
                                        <span class="fa fa-globe w-3"></span>
                                    </div>
                                    <div class="text pl-3">
                                        <p><span>Website:</span> <a href="acc.afrikbook.com">afrikbook.accounting.con</a></p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>


{% endblock content %}

index/templates/index.html
{% extends 'base.html' %}

{% block content %}

<!-- carosel -->
<div class="hero-wra">
	<div class="home-slider owl-carousel">
		<div class="slider-item  flex justify-center" style="background-image:url(media/images/bg_11.png);">
			<div class="overlay"></div>
			<div class="container">
				<div
					class="flex items-center justify-center no-gutters slider-text align-items-center justify-content-center">
					<div class="col-md-8 ftco-animate">
						<div class="text w-100 text-center">
							<h2 class="text-primary">We Help Business Grow</h2>
							<h1 class="mb-4">We Help You Businesses Innovate and Grow</h1>
							<p><a href="https://acc.afrikbook.com/NewCompany" class="bg-primary p-2 rounded-lg">Connect with us</a></p>
						</div>
					</div>
				</div>
			</div>
		</div>

		<div class="slider-item  flex justify-center" style="background-image:url(media/images/bg_22.png);">
			<div class="overlay"></div>
			<div class="container">
				<div
					class="flex items-center justify-center no-gutters slider-text align-items-center justify-content-center">
					<div class="col-md-8 ftco-animate">
						<div class="text w-100 text-center">
							<h2>We Support Business</h2>
							<h1 class="mb-4">The Best Business Support</h1>
							<p><a href="https://acc.afrikbook.com/NewCompany" class="bg-primary p-2 rounded-lg">Connect with us</a></p>
						</div>
					</div>
				</div>
			</div>
		</div>

		<div class="slider-item  flex justify-center" style="background-image:url(media/images/bg_33.jpg);">
			<div class="overlay"></div>
			<div class="container">
				<div
					class="flex items-center justify-center no-gutters slider-text align-items-center justify-content-center">
					<div class="col-md-8 ftco-animate">
						<div class="text w-100 text-center">
							<h2>We Give Advice</h2>
							<h1 class="mb-4">Expert Financial Advice</h1>
							<p><a href="https://acc.afrikbook.com/NewCompany" class="bg-primary p-2 rounded-lg">Connect with us</a></p>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

{% include 'components/first.html' %}

{% include 'components/second.html' %}

<!-- {% include 'components/acheivements.html' %} -->

{% include 'components/signup.html' %}

<!-- {% include 'components/testimonies.html' %} -->


{% include 'components/plans.html' %}






{% endblock content %}

index/templates/services.html
{% extends 'base.html' %}

{% block content %}

<section class="flex justify-center hero-wrap hero-wrap-2 h-full  mb-6" style="background-image: url('/media/images/bg_2.jpg');" data-stellar-background-ratio="0.5">
    <div class="overlay"></div>
    
    <div class="container w-7/12">
      <div class="flex items-center no-gutters slider-text align-items-end">
        <div class="col-md-9 ftco-animate pb-5">
            <p class="breadcrumbs mb-2"><span class="mr-2"><a href="{% url 'index:home'%}">Home <i class="ion-ios-arrow-forward"></i></a></span> <span>Servived <i class="ion-ios-arrow-forward"></i></span></p>
          <h1 class="mb-0 bread">Services</h1>
        </div>
      </div>
    </div>
</section>
{% include 'components/second.html' %}

{% include 'components/first.html' %}

{% include 'components/plans.html' %}

{% include 'components/signup.html' %}

{% endblock content %}

templates/base.html
{% load static %}
{% load static tailwind_tags %}
<!DOCTYPE html>
<html lang="en">
	<head>
    <title>Afrikbook</title>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<meta http-equiv="X-UA-Compatible" content="ie=edge">
		{% tailwind_css %}
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
 
		<link rel="stylesheet" href="{% static 'css/animate.css' %}">
		<link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/owl.theme.default.min.css' %}">
		<link rel="stylesheet" href="{% static 'css/flaticon.css' %}">
        <link rel="stylesheet" href="{% static 'css/main.css' %}">

		<!-- Jquery -->
        <script src="{% static 'js/jquery.js' %}"></script>
        <script src="{% static 'js/jquery.min.js' %}"></script>
       
	</head>

	<body class="bg-gray-50 font-serif  leading-normal tracking-normal relative h-screen w-full">
		
		<!-- {% include 'components/feedback.html' %} -->
		{% include 'components/Navbar.html' %}
		{% include 'components/Sidebar.html' %}
		{% include 'messages.html' %}
		{% block content %}
				
		{% endblock content %}
		
		{% include 'components/Footer.html' %}
		
		
		<script src="{% static 'js/jquery.animateNumber.min.js' %}"></script>
		<script src="{% static 'js/jquery.waypoints.min.js' %}"></script>
		<script src="{% static 'js/jquery.stellar.min.js' %}"></script>
		<script src="{% static 'js/owl.carousel.min.js' %}"></script>
		<script src="{% static 'js/feedback.js' %}"></script>
		<script src="{% static 'js/myjs.js' %}"></script>
		
		
	</body>
	
</html>

templates/components/Footer.html
<footer class="footer bg-primary font-sans mt-6 w-full">
    <div class="container-fluid px-lg-5">
        <div class="flex flex-col md:flex-row">
            <div class="flex-auto w-full md:w-9/12 p-8">
                <div class="flex flex-col md:flex-row gap-6">
                    <div class="w-full mb-md-0 mb-4">
                        <h2 class="text-white mb-4 uppercase font-semibold">About us</h2>
                        <p class="text-slate-400">Our accounting software is a comprehensive, user-friendly tool designed to streamline financial management for businesses of all sizes. With an intuitive interface, it automates complex tasks such as bookkeeping, invoicing, expense tracking, payroll processing, and financial reporting. Built with robust security, it ensures that sensitive financial data remains protected at all times.</p>
                        <ul class="flex gap-10 mt-6">
                            <li class="ftco-animate"><a href="#" data-toggle="tooltip" data-placement="top" title="Twitter"><span class="fa fa-twitter"></span></a></li>
                            <li class="ftco-animate"><a href="#" data-toggle="tooltip" data-placement="top" title="Facebook"><span class="fa fa-facebook"></span></a></li>
                            <li class="ftco-animate"><a href="#" data-toggle="tooltip" data-placement="top" title="Instagram"><span class="fa fa-instagram"></span></a></li>
                        </ul>
                    </div>
                    <div class="w-full">
                        <div class="justify-content-center">
                            <div class="">
                                <div class="flex flex-col md:flex-row gap-20">
                                    <div class="col-md-4 mb-md-0 mb-4">
                                        <h2 class="text-white mb-4 uppercase font-semibold">Services</h2>
                                        <ul class="text-slate-400 ">
                                            <li><a href="#" class="my-4">Automated Bookkeeping</a></li>
                                            <li><a href="#" class="my-4">Invoicing and Billing</a></li>
                                            <li><a href="#" class="my-4">Expense Tracking</a></li>
                                            <li><a href="#" class="my-4">Multi-User Access</a></li>
                                        </ul>
                                    </div>
                                    <div class="col-md-4 mb-md-0 mb-4">
                                        <h2 class="text-white mb-4 uppercase font-semibold">Discover</h2>
                                        <ul class="text-slate-400">
                                            <li><a href="{% url 'index:about' %}" class="py-1 d-block">About</a></li>
                                            <li><a href="{% url 'index:contact' %}" class="py-1 d-block">Contact</a></li>
                                            <li><a href="#" class="py-1 d-block">Terms &amp; Conditions</a></li>
                                            <li><a href="#" class="py-1 d-block">Policies</a></li>
                                        </ul>
                                    </div>
                                    <div class="col-md-4 mb-md-0 mb-4">
                                        <h2 class="text-white mb-4 uppercase font-semibold">Resources</h2>
                                        <ul class="text-slate-400">
                                            <li><a href="#" class="py-1 d-block">Security</a></li>
                                            <li><a href="#" class="py-1 d-block">Global</a></li>
                                            <li><a href="#" class="py-1 d-block">Charts</a></li>
                                            <li><a href="#" class="py-1 d-block">Privacy</a></li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                
            </div>
            <div class="flex-auto w-full md:w-3/12 bg-gray-900 p-8">
                <h2 class="text-white mb-4 uppercase font-bold">Free consultation</h2>
                <div id="form-message-success" class="mb-4 {% if message.tags == 'success' %} text-green-600 {%else%} text-red-500 {% endif %}">
                    {% for message in messages %}
                         {{message}}
                    {% endfor %}
                </div>
                <form method="post" action="{% url 'index:contact' %}" class="form-consultation">
                    {% csrf_token %}
                    <div class="mb-4">
                        <input type="text" name="fullname" class="w-full bg-gray-900 rounded-lg text-slate-400 text-sm" placeholder="Your Name" required>
                    </div>
                    <div class="mb-4">
                        <input type="email" name="email" class="w-full bg-gray-900 rounded-lg text-slate-400 text-sm" placeholder="Your Email" required>
                    </div>
                    <div class="mb-4">
                        <input type="text" name="subject" class="w-full bg-gray-900 rounded-lg text-slate-400 text-sm" placeholder="Subject" required>
                    </div>
                    <div class="mb-4">
                        <textarea name="message" id="" cols="30" rows="3" class="w-full bg-gray-900 rounded-lg text-slate-400 text-sm" placeholder="Message" required></textarea>
                    </div>
                    <div class="form-group">
                        <button type="submit" class="w-full bg-green-600 py-2 submit px-3 text-white">Send A Message</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</footer>

templates/components/Navbar.html
<nav class="flex justify-center bg-primary" id="ftco-navba">
    <div class="container flex items-center text-white justify-between px-2 py-6">
        <a class="hidden lg:block text-2xl font-bold font-sans" href="{% url 'index:home' %}">Afrikbook Accounting</a>
        <div class="hidden lg:block" id="ftco-nav">
            <ul class="flex items-center uppercase text-sm font-semibold font-sans gap-8">
              <li class="transition  duration-300 delay-50 hover:text-green-600"><a href="{% url 'index:home' %}" class="nav-link">Home</a></li>
              <li class="ntransition  duration-300 delay-50 hover:text-green-600"><a href="{% url 'index:about' %}" class="nav-link">About</a></li>
              <!-- <li class="ntransition  duration-300 delay-50 hover:text-green-600"><a href="{% url 'index:services' %}" class="nav-link">Services</a></li> -->
              <li class="ntransition  duration-300 delay-50 hover:text-green-600"><a href="{% url 'index:mannual' %}" class="nav-link">Mannual</a></li>
              <!-- <li class="ntransition  duration-300 delay-50 hover:text-green-600"><a href="{% url 'index:blog' %}" class="nav-link">Blog</a></li> -->
              <li class="ntransition  duration-300 delay-50 hover:text-green-600"><a href="{% url 'index:contact' %}" class="nav-link">Contact</a></li>
            </ul>
        </div>
        <form action="#" class="searchform order-sm-start order-lg-last">
            <div class="form-group flex justify-center items-center">
                <input type="text" class="outline-none rounded-l text-gray-600" placeholder="Search">
                <button type="submit" placeholder="" class="form-control search bg-primary h-10 w-10 md:w-20"><span class="fa fa-search"></span></button>
            </div>
        </form>
        <div class="block lg:hidden text-white flex gap-2">
            <button @click="open = !open" class="toggle inline-flex items-center justify-center p-2  rounded-md  focus:outline-none " x-bind:aria-label="open ? 'Close main menu' : 'Main menu'" x-bind:aria-expanded="open">
                <svg class="w-6 h-6" stroke="currentColor" fill="none" viewBox="0 0 24 24">
                <path :class="{'hidden': open, 'inline-flex': !open }" class="inline-flex" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16" />
                <path :class="{'hidden': !open, 'inline-flex': open }" class="hidden" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
                </svg>
            </button>
        </div>
    
     
    </div>
  </nav>
<!-- END nav -->

<script>
    $(".toggle").click(function(){
       $('#side-nav').slideToggle('slow')
    //    $('#side-nav').toggle('slow')
    })
</script>

templates/components/Sidebar.html
<div class="hidden  bg-primary py-6" id="side-nav">
    <ul class="flex flex-col items-start  uppercase text-sm font-semibold font-sans">
      <a href="{% url 'index:home' %}" class="transition  duration-300 delay-50 w-full p-2 hover:bg-gray-900 mb-2">Home</a>
      <a href="{% url 'index:about' %}" class="transition  duration-300 delay-50 w-full p-2 hover:bg-gray-900 mb-2">About</a>
      {% comment %} <a href="{% url 'index:services' %}" class="transition  duration-300 delay-50 w-full p-2 hover:bg-gray-900 mb-2">Services</a> {% endcomment %}
      <a href="{% url 'index:mannual' %}" class="transition  duration-300 delay-50 w-full p-2 hover:bg-gray-900 mb-2">Mannual</a>
      <a href="{% url 'index:contact' %}" class="transition  duration-300 delay-50 w-full p-2 hover:bg-gray-900 mb-2">Contact</a>
    </ul>
</div>

templates/components/acheivements.html
<section class="flex justify-center my-10" id="section-counter">
	<div class="container w-10/12 md:w-7/12">
		<div class="flex flex-col md:flex-row items-center justify-between">
			<div class="mb-6 justify-content-center counter-wrap ftco-animate">
				<div class="block-18 text-center">
					<div class="text">
						<strong class="number text-[50px] mb-10 text-primary font-sans" data-number="5">0</strong>
					</div>
					<div class="text">
						<span class="uppercase font-sans">Years of Experienced</span>
					</div>
				</div>
			</div>
			<div class="mb-6 justify-content-center counter-wrap ftco-animate">
				<div class="block-18 text-center">
					<div class="text">
						<strong class="number text-[50px] mb-10 text-primary font-sans" data-number="8500">0</strong>
					</div>
					<div class="text">
						<span class="uppercase font-sans">Cases Completed</span>
					</div>
				</div>
			</div>
			<div class="mb-6 justify-content-center counter-wrap ftco-animate">
				<div class="block-18 text-center">
					<div class="text">
						<strong class="number text-[50px] mb-10 text-primary font-sans" data-number="20">0</strong>
					</div>
					<div class="text">
						<span class="uppercase font-sans">Awards Won</span>
					</div>
				</div>
			</div>
			<div class="mb-6 justify-content-center counter-wrap ftco-animate">
				<div class="block-18 text-center">
					<div class="text">
						<strong class="number text-[50px] mb-10 text-primary font-sans" data-number="50">0</strong>
					</div>
					<div class="text">
						<span class="uppercase font-sans">Expert Consultant</span>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>

templates/messages.html
{% for message in messages %}
    <div class="alert {% if message.tags == 'success' %} bg-green-600 {%else%} bg-red-500 {% endif %} p-2 text-white alert-dismissible fade show" role="alert">
        {{message}}
        <button type="button" class="close" data-dismiss="alert" aria-label="close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
{% endfor %}
    